=== gflanagan/thesis-paper/src/parser/DSpace Schema Release 1/DSpace_XMLSchema_Release1_v3.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema">
 
 <xs:element name="designFile" abstract="false">
  <xs:complexType>
   <xs:sequence>
 
    <xs:element name="DsProject" type="DsProject"/>
    <xs:element name="DsProduct" type="DsProduct" maxOccurs="unbounded"/>
    <xs:element name="DsRelationship" type="DsRelationship" maxOccurs="unbounded"/>

   </xs:sequence>
  </xs:complexType>
 </xs:element>

<xs:complexType name="DsRoot" abstract="true">
 <xs:sequence>
  <xs:element name="globalId" type="xs:string"/>
  <xs:element name="name" type="xs:string" default="" minOccurs="0" maxOccurs="1"/>
  <xs:element name="description" type="xs:string" default="" minOccurs="0" maxOccurs="1"/>
 </xs:sequence>
</xs:complexType>

<xs:complexType name="DsObject" abstract="true">
 <xs:complexContent>
  <xs:extension base="DsRoot"></xs:extension>
 </xs:complexContent>
</xs:complexType>

<xs:complexType name="DsProject" abstract="false">
 <xs:complexContent>
  <xs:extension base="DsObject"></xs:extension>
 </xs:complexContent>
</xs:complexType>

<xs:complexType name="DsProduct" abstract="true">
 <xs:complexContent>
  <xs:extension base="DsObject">
   <xs:sequence>
    <xs:element name="objectPlacement" type="DsLocalPlacement"/>
    <xs:element name="representation" type="DsShapeRepresentation"/> 
   </xs:sequence>
  </xs:extension>
 </xs:complexContent>
</xs:complexType>

<xs:complexType name="DsSpatialStructureElement" abstract="true">
 <xs:complexContent>
  <xs:extension base="DsProduct"></xs:extension>
 </xs:complexContent>
</xs:complexType>

<xs:complexType name="DsBuilding" abstract="false">
 <xs:complexContent>
  <xs:extension base="DsSpatialStructureElement"></xs:extension>
 </xs:complexContent>
</xs:complexType>

<xs:complexType name="DsBuildingStorey" abstract="false">
 <xs:complexContent>
  <xs:extension base="DsSpatialStructureElement"></xs:extension>
 </xs:complexContent>
</xs:complexType>

<xs:complexType name="DsBuildingElement" abstract="true">
 <xs:complexContent>
  <xs:extension base="DsProduct"></xs:extension>
 </xs:complexContent>
</xs:complexType>

<xs:complexType name="DsWallStandardCase" abstract="false">
 <xs:complexContent>
  <xs:extension base="DsBuildingElement"></xs:extension>
 </xs:complexContent>
</xs:complexType>

<xs:complexType name="DsRelationship" abstract="true">
 <xs:complexContent>
  <xs:extension base="DsRoot"></xs:extension>
 </xs:complexContent>
</xs:complexType>

<xs:complexType name="DsRelAggregates" abstract="false">
 <xs:complexContent>
  <xs:extension base="DsRelationship">
   <xs:sequence>
    <xs:element name="relatingObjectGUID" type="xs:string"/>
    <xs:element name="relatedObjectGUID" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
   </xs:sequence>
  </xs:extension>
 </xs:complexContent>
</xs:complexType>

<xs:complexType name="DsRelContainedInSpatialStructure" abstract="false">
 <xs:complexContent>
  <xs:extension base="DsRelationship">
   <xs:sequence>
    <xs:element name="relatingStructureGUID" type="xs:string"/>
    <xs:element name="relatedElementGUID" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
   </xs:sequence>
  </xs:extension>
 </xs:complexContent>
</xs:complexType>

<xs:complexType name="DsLocalPlacement" abstract="false">
 <xs:sequence>
  <xs:element name="relativePlacement" type="DsCartesianPoint"/>
 </xs:sequence>
</xs:complexType>

<xs:complexType name="DsShapeRepresentation" abstract="false">
 <xs:sequence>
  <xs:element name="item" type="DsPolyline" minOccurs="1" maxOccurs="unbounded"/>
 </xs:sequence>
</xs:complexType>

<xs:complexType name="DsPolyline" abstract="false">
 <xs:sequence>
  <xs:element name="point" type="DsCartesianPoint" minOccurs="4" maxOccurs="unbounded"/>
 </xs:sequence>
</xs:complexType>


 <xs:complexType name="DsCartesianPoint" abstract="false">
   <xs:attribute name="x" type="xs:double"/>
  <xs:attribute name="y" type="xs:double"/>
 </xs:complexType>
 
<!--
 <xs:complexType name="DsCartesianPoint" abstract="false">
 <xs:sequence>
  <xs:element name="x" type="xs:double"/>
 <xs:element name="y" type="xs:double"/>
  </xs:sequence>
</xs:complexType>
-->
 


</xs:schema>

=== gflanagan/thesis-paper/src/parser/DSpace Schema Release 1/DSpace_XML_Release_1_v3.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    DSpace Release 1
    Example XML 3

    Purpose:
        Introduce multiple wall building elements.
        
    Description:
        1 project
        1 building
        1 building storey
        4 standard wall
        
        The project decomposes to the building.
        The building decomposes to the storey.
        The storey contains the wall.
        
        The footprint of the building and storey is a 50mx50m square,
        translated by (10,10).
        
        Two of the wall footprints are 1mx50m rectangles, translated 
        by (10,10) and (60,10) respectively. The other two wall 
        footprints are 50mx1m rectangles, translated by (10,10) and
        (10,60) respectively. The four walls cover the perimeter of the
        building storey.
-->

<designFile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../DSpace_XMLSchema_Release1_v3.xsd">

        <DsProject>
            <globalId>hd83jdjsd82jjdjd</globalId>
            <name>Cartesium</name>
            <description>The building where DSpace is being developed.</description>
        </DsProject>
    
        <DsProduct xsi:type="DsBuilding">
        <globalId>9292929292929</globalId>
        <name>Cartesium</name>
        <description>The building where DSpace is being developed.</description>
        <objectPlacement>
            <relativePlacement x="10" y="10"/>
        </objectPlacement>
            <representation>
                <item>
                    <point x="0" y="0"/>
                    <point x="0" y="50"/>
                    <point x="50" y="50"/>
                    <point x="50" y="0"/>
                    <point x="0" y="0"/>
                </item>
            </representation>
        </DsProduct>
     
    <DsProduct xsi:type="DsBuildingStorey">
        <globalId>82hfjhkd38h3n3fk3</globalId>
        <name>Floor 3</name>
        <description>The storey where Mehul, Greg, Nikhil, and Carl are developing DSpace.</description>
        
        <objectPlacement>
            <relativePlacement x="10" y="10"/>
        </objectPlacement>
        <representation>
            <item>
                <point x="0" y="0"/>
                <point x="0" y="50"/>
                <point x="50" y="50"/>
                <point x="50" y="0"/>
                <point x="0" y="0"/>
            </item>
        </representation>
    </DsProduct>
    
    <DsProduct xsi:type="DsWallStandardCase">
        <globalId>3rh09u3nd038hohlskndA</globalId>
        <name>Boundary wall A</name>
        <description>A wall marking one side of the Cartesium.</description>
        
        <objectPlacement>
            <relativePlacement x="10" y="10"/>
        </objectPlacement>
        <representation>
            <item>
                <point x="0" y="0"/>
                <point x="0" y="50"/>
                <point x="1" y="50"/>
                <point x="1" y="0"/>
                <point x="0" y="0"/>
            </item>
        </representation>
    </DsProduct>
    
    <DsProduct xsi:type="DsWallStandardCase">
        <globalId>3rh09u3nd038hohlskndB</globalId>
        <name>Boundary wall B</name>
        <description>A wall marking one side of the Cartesium.</description>
        
        <objectPlacement>
            <relativePlacement x="10" y="10"/>
        </objectPlacement>
        <representation>
            <item>
                <point x="0" y="0"/>
                <point x="50" y="0"/>
                <point x="50" y="1"/>
                <point x="0" y="1"/>
                <point x="0" y="0"/>
            </item>
        </representation>
    </DsProduct>
    
    <DsProduct xsi:type="DsWallStandardCase">
        <globalId>3rh09u3nd038hohlskndC</globalId>
        <name>Boundary wall C</name>
        <description>A wall marking one side of the Cartesium.</description>
        
        <objectPlacement>
            <relativePlacement x="59" y="10"/>
        </objectPlacement>
        <representation>
            <item>
                <point x="0" y="0"/>
                <point x="0" y="50"/>
                <point x="1" y="50"/>
                <point x="1" y="0"/>
                <point x="0" y="0"/>
            </item>
        </representation>
    </DsProduct>
    
    
    <DsProduct xsi:type="DsWallStandardCase">
        <globalId>3rh09u3nd038hohlskndD</globalId>
        <name>Boundary wall D</name>
        <description>A wall marking one side of the Cartesium.</description>
        
        <objectPlacement>
            <relativePlacement x="60" y="10"/>
        </objectPlacement>
        <representation>
            <item>
                <point x="0" y="0"/>
                <point x="50" y="0"/>
                <point x="50" y="1"/>
                <point x="0" y="1"/>
                <point x="0" y="0"/>
            </item>
        </representation>
    </DsProduct>
    
    <DsRelationship xsi:type="DsRelAggregates">
        <globalId>osn8nksjnohonwnc83sjkdbsd</globalId>
        <relatingObjectGUID>hd83jdjsd82jjdjd</relatingObjectGUID>
        <relatedObjectGUID>9292929292929</relatedObjectGUID>
    </DsRelationship>
    
    <DsRelationship xsi:type="DsRelAggregates">
        <globalId>jfujkhsfhui2riukbdajkadkj</globalId>
        <relatingObjectGUID>9292929292929</relatingObjectGUID>
        <relatedObjectGUID>82hfjhkd38h3n3fk3</relatedObjectGUID>
    </DsRelationship>
    
    <DsRelationship xsi:type="DsRelContainedInSpatialStructure">
        <globalId>09384i28y34kjhskjdfhku2y34</globalId>
        <relatingStructureGUID>82hfjhkd38h3n3fk3</relatingStructureGUID>
        <relatedElementGUID>3rh09u3nd038hohlskndA</relatedElementGUID>
        <relatedElementGUID>3rh09u3nd038hohlskndB</relatedElementGUID>
        <relatedElementGUID>3rh09u3nd038hohlskndC</relatedElementGUID>
        <relatedElementGUID>3rh09u3nd038hohlskndD</relatedElementGUID>
    </DsRelationship>

    
</designFile>

=== gflanagan/thesis-paper/src/parser/DSpace Schema Release 1/DSpace_XML_Release_1_v1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    DSpace Release 1
    Example XML 1

    Purpose:
        Test out the basic aggregation relationships that are mandatory
        
    Description:
        1 Project
        1 Building
        1 Building storey
        
        The project decomposes to the building.
        The building decomposes to the storey.
        
        The footprint of the building and storey is a 50x50 square,
        translated by (10,10).
-->

<designFile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../DSpace_XMLSchema_Release1_v3.xsd">

        <DsProject>
            <globalId>hd83jdjsd82jjdjd</globalId>
            <name>Cartesium</name>
            <description>The building where DSpace is being developed.</description>
        </DsProject>
    
        <DsProduct xsi:type="DsBuilding">
        <globalId>9292929292929</globalId>
        <name>Cartesium</name>
        <description>The building where DSpace is being developed.</description>
        <objectPlacement>
            <relativePlacement x="10" y="10"/>
        </objectPlacement>
            <representation>
                <item>
                    <point x="0" y="0"/>
                    <point x="0" y="50"/>
                    <point x="50" y="50"/>
                    <point x="50" y="0"/>
                    <point x="0" y="0"/>
                </item>
            </representation>
        </DsProduct>
     
    <DsProduct xsi:type="DsBuildingStorey">
        <globalId>82hfjhkd38h3n3fk3</globalId>
        <name>Floor 3</name>
        <description>The storey where Mehul, Greg, Nikhil, and Carl are developing DSpace.</description>
        
        <objectPlacement>
            <relativePlacement x="10" y="10"/>
        </objectPlacement>
        <representation>
            <item>
                <point x="0" y="0"/>
                <point x="0" y="50"/>
                <point x="50" y="50"/>
                <point x="50" y="0"/>
                <point x="0" y="0"/>
            </item>
        </representation>
    </DsProduct>
    
    <DsRelationship xsi:type="DsRelAggregates">
        <globalId>osn8nksjnohonwnc83sjkdbsd</globalId>
        <relatingObjectGUID>hd83jdjsd82jjdjd</relatingObjectGUID>
        <relatedObjectGUID>9292929292929</relatedObjectGUID>
    </DsRelationship>
    
    <DsRelationship xsi:type="DsRelAggregates">
        <globalId>jfujkhsfhui2riukbdajkadkj</globalId>
        <relatingObjectGUID>9292929292929</relatingObjectGUID>
        <relatedObjectGUID>82hfjhkd38h3n3fk3</relatedObjectGUID>
    </DsRelationship>

    
</designFile>
